#!/usr/bin/env node

const childProcess = require('child_process');
var spawn = require('child-process-promise').spawn;
const Log = require('./lib/log');
const regions = require('./lib/serverlessHelpers').getRegions();

console.log(`Removing gobuster from ${regions.length} regions`)

async function asyncForEach(array, callback) {
  for (let index = 0; index < array.length; index++) {
    await callback(array[index], index, array)
  }
}

(async function () {
  asyncForEach(regions, async (region) => {
    let init = Log.loading(`Removing deployment from ${region} `);
    let err;
    await spawn('serverless', ['remove', `--region ${region}`]).catch(function (err) {
      init.status.error(init.finished);
      err = true;
    })
    if (!err) {
      init.status.success(init.finished);
    }

  })
})()